### ISSUE TITLE
大佬请问 snippets,document文件是自动生成吗，还是手写的呢 https://github.com/HULANG-BTB/element-ui-helper/tree/master/src/document/zh-CN

### ISSUE THREAD

**Issue by hytStart** [HULANG-BTB/element-ui-helper#1]
大佬请问 snippets,document文件是自动生成吗，还是手写的呢 https://github.com/HULANG-BTB/element-ui-helper/tree/master/src/document/zh-CN

**Comment by HULANG-BTB** [comment]
> 大佬请问 snippets,document文件是自动生成吗，还是手写的呢 https://github.com/HULANG-BTB/element-ui-helper/tree/master/src/document/zh-CN

document目录下提供了document-builder，通过官方文档中提供的md文件生成TS文档（生成的文档并不完全的可靠，因为官方文档并没有固定的格式，所以生成之后还需要自己手动检测文档是否合格），package.json中有标注生成脚本，snippets这个插件暂时还不支持，并且未来没有打算加入snippets的打算，因为element官方的插件中已经提供了这项功能，这个插件只是起到一个辅助性的作用。

[document-builder](https://github.com/HULANG-BTB/element-ui-helper/blob/master/src/document/document-builder.js)

**Comment by hytStart** [comment]
> > 大佬请问 snippets,document文件是自动生成吗，还是手写的呢 https://github.com/HULANG-BTB/element-ui-helper/tree/master/src/document/zh-CN
> 
> document目录下提供了document-builder，通过官方文档中提供的md文件生成TS文档（生成的文档并不完全的可靠，因为官方文档并没有固定的格式，所以生成之后还需要自己手动检测文档是否合格），package.json中有标注生成脚本，snippets这个插件暂时还不支持，并且未来没有打算加入snippets的打算，因为element官方的插件中已经提供了这项功能，这个插件只是起到一个辅助性的作用。
> 
> [document-builder](https://github.com/HULANG-BTB/element-ui-helper/blob/master/src/document/document-builder.js)

好的，感谢 @HULANG-BTB
